### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by SnkyFrsh** [kalebbroo/plex_music_bot#7]
Getting the below error when trying to run in docker

```
2023-05-30 18:31:45 [2023-05-30 18:31:45] [INFO    ] discord.client: logging in using static token
2023-05-30 18:31:45 Traceback (most recent call last):
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
2023-05-30 18:31:45     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
2023-05-30 18:31:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\asyncio\base_events.py", line 1112, in create_connection
2023-05-30 18:31:45     transport, protocol = await self._create_connection_transport(
2023-05-30 18:31:45                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\asyncio\base_events.py", line 1145, in _create_connection_transport
2023-05-30 18:31:45     await waiter
2023-05-30 18:31:45   File "C:\Python\Lib\asyncio\sslproto.py", line 574, in _on_handshake_complete
2023-05-30 18:31:45     raise handshake_exc
2023-05-30 18:31:45   File "C:\Python\Lib\asyncio\sslproto.py", line 556, in _do_handshake
2023-05-30 18:31:45     self._sslobj.do_handshake()
2023-05-30 18:31:45   File "C:\Python\Lib\ssl.py", line 979, in do_handshake
2023-05-30 18:31:45     self._sslobj.do_handshake()
2023-05-30 18:31:45 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)
2023-05-30 18:31:45 
2023-05-30 18:31:45 The above exception was the direct cause of the following exception:
```

Which is then followed by the rest;

```
2023-05-30 18:31:45 Traceback (most recent call last):
2023-05-30 18:31:45   File "C:\app\plex_music_bot.py", line 1051, in <module>
2023-05-30 18:31:45     bot.run(TOKEN)
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\discord\client.py", line 860, in run
2023-05-30 18:31:45     asyncio.run(runner())
2023-05-30 18:31:45   File "C:\Python\Lib\asyncio\runners.py", line 190, in run
2023-05-30 18:31:45     return runner.run(main)
2023-05-30 18:31:45            ^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\asyncio\runners.py", line 118, in run
2023-05-30 18:31:45     return self._loop.run_until_complete(task)
2023-05-30 18:31:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\asyncio\base_events.py", line 653, in run_until_complete
2023-05-30 18:31:45     return future.result()
2023-05-30 18:31:45            ^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\discord\client.py", line 849, in runner
2023-05-30 18:31:45     await self.start(token, reconnect=reconnect)
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\discord\client.py", line 777, in start
2023-05-30 18:31:45     await self.login(token)
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\discord\client.py", line 612, in login
2023-05-30 18:31:45     data = await self.http.static_login(token)
2023-05-30 18:31:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\discord\http.py", line 801, in static_login
2023-05-30 18:31:45     data = await self.request(Route('GET', '/users/@me'))
2023-05-30 18:31:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\discord\http.py", line 624, in request
2023-05-30 18:31:45     async with self.__session.request(method, url, **kwargs) as response:
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
2023-05-30 18:31:45     self._resp = await self._coro
2023-05-30 18:31:45                  ^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\client.py", line 536, in _request
2023-05-30 18:31:45     conn = await self._connector.connect(
2023-05-30 18:31:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\connector.py", line 540, in connect
2023-05-30 18:31:45     proto = await self._create_connection(req, traces, timeout)
2023-05-30 18:31:45             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
2023-05-30 18:31:45     _, proto = await self._create_direct_connection(req, traces, timeout)
2023-05-30 18:31:45                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
2023-05-30 18:31:45     raise last_exc
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
2023-05-30 18:31:45     transp, proto = await self._wrap_create_connection(
2023-05-30 18:31:45                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30 18:31:45   File "C:\Python\Lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
2023-05-30 18:31:45     raise ClientConnectorCertificateError(req.connection_key, exc) from exc
2023-05-30 18:31:45 aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]
```

Unsure on the approach to correct this problem.

**Comment by kalebbroo** [comment]
Do you have your BASEURL 'https'? should be 'http'

https://python-plexapi.readthedocs.io/en/latest/modules/server.html

**Comment by SnkyFrsh** [comment]
Found out I was building the docker instance wrong lol. Its working now, but there are some teething issues when trying to play something

```
2023-05-31 10:37:44   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
2023-05-31 10:37:44     hosts = await asyncio.shield(host_resolved)
2023-05-31 10:37:44             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-31 10:37:44   File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 874, in _resolve_host
2023-05-31 10:37:44     addrs = await self._resolver.resolve(host, port, family=self._family)
2023-05-31 10:37:44             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-31 10:37:44   File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
2023-05-31 10:37:44     infos = await self._loop.getaddrinfo(
2023-05-31 10:37:44             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-31 10:37:44   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
2023-05-31 10:37:44     return await self.run_in_executor(
2023-05-31 10:37:44            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-31 10:37:44   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
2023-05-31 10:37:44     result = self.fn(*self.args, **self.kwargs)
2023-05-31 10:37:44              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-31 10:37:44   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
2023-05-31 10:37:44     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-05-31 10:37:44                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-31 10:37:44 socket.gaierror: [Errno -2] Name or service not known
2023-05-31 10:37:44 
2023-05-31 10:37:44 The above exception was the direct cause of the following exception:
```

**Comment by kalebbroo** [comment]
Can you share the full error with me? I am currently not receiving any errors.

**Comment by SnkyFrsh** [comment]
Am not seeing anything else since rebuilding the bot. Not sure what actually caused it

**Comment by kalebbroo** [comment]
cool, I will close this issue. Just open a new one if you come across anything else strange. it is still in beta so there may be some bugs I need to fix.
